spring.application.name=sd_02
# Config da BD PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/sd_monitorizacao
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Config JPA
# 'update' cria tabelas se não existirem
spring.jpa.hibernate.ddl-auto=update
# Mostrar as queries no terminal
spring.jpa.show-sql=true
# Dialeto de PostgreSQL
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Config timestamp
# spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false